apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Chart.Name }}-{{ .Values.image.tag }}
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.labels }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.health }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.health }}
              port: http
