spring:
  application:
    name: MetricsApp
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
