== Grafana Agent Flow on K8S

=== Prerequisites

Create a separate namespace called `ga`.
[source,shell]
----
kubectl create namespace ga
----


=== Components installation

==== Grafana Agent in `flow` mode

https://grafana.com/docs/agent/latest/flow/get-started/install/kubernetes/[Installation docs]

NAMESPACE:: ga
RELEASE_NAME::  grafana-agent-flow

[source,shell]
----
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm install --namespace ga grafana-agent-flow grafana/grafana-agent
----

Then check installation
[source,shell]
----
helm list -n ga
----

.Expected check result
[source,text]
----
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
grafana-agent-flow      ga              1               2024-09-09 10:25:10.960079 +0200 CEST   deployed        grafana-agent-0.42.0    v0.42.0

----

.Port forwarding
[source,shell]
----
export POD_NAME=$(kubectl get pods --namespace ga -l "app.kubernetes.io/instance=grafana-agent-flow" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace ga port-forward $POD_NAME 8888:80
----


==== Simple application that supplies metrics on port `8080`.

* spring boot app w/ actuator and micrometer/prometheus

.Port forwarding
[source,shell]
----
export POD_NAME=$(kubectl get pods --namespace ga -l "app=metrics-app" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace ga port-forward $POD_NAME 8080
----

.Scaling
[source,shell]
----
kubectl -n ga scale deployment demo-metrics-app --replicas=3
----

==== Prometheus

[source,shell]
----
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

helm install -n ga prometheus prometheus-community/prometheus
# --or--
helm install --namespace ga  -f ./config/prometheus/prometheus.yaml prometheus prometheus-community/prometheus

helm -n ga list
----

The built-in remote write receiver can be enabled by setting the `--web.enable-remote-write-receiver` command line flag. When enabled, the remote write receiver endpoint is `/api/v1/write`.

.Prometheus config overrides
[source,yaml]
----
include::config/prometheus/prometheus.yaml[]
----


[source,shell]
----
export POD_NAME=$(kubectl get pods --namespace ga -l "app.kubernetes.io/name=prometheus,app.kubernetes.io/instance=prometheus" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace ga port-forward $POD_NAME 9090

----


.Tear down prometheus installation
[source,shell]
----
helm uninstall -n ga prometheus
----

=== Grafana Agent configuration

* https://grafana.com/docs/agent/latest/flow/tasks/configure/configure-kubernetes/[Official config guide]

.Customized values.yaml configuration
[source,yaml]
----
include::config/ga/values.yaml[]
----

.Check new values in action
[source,shell]
----
helm upgrade -n ga grafana-agent-flow grafana/grafana-agent -f ./config/ga/values.yaml
----


=== Debugging

.Debug
[source,shell]
----
kubectl run -it --rm --restart=Never -n ga busybox --image=gcr.io/google-containers/busybox sh
----

.Simple metrics to trace
```
application_ready_time_seconds{main_application_class="pl.sparkidea.demo.metricsapp.MetricsAppApplication"}
```


[source,shell]
----
sudo systemctl stop firewalld
----
